name: Build-Deploy-Pipelines-preprod
on:
  push:
    branches:
      - 'q0-pipeline'
      - 'q1-pipeline'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - 'q0-pipeline'
      - 'q1-pipeline'
    paths-ignore:
      - '**.md'